### ISSUE TITLE
[Feature] change pre-specified themes

### ISSUE THREAD

**Issue by bekirburakcelik** [koenderks/rcityviews#14]
I want to make changes to the pre-specified themes. I like the themes very much and I want to use them, but sometimes I just want the city name and coordinates to be deleted or the buildings not to be rendered. is such a thing possible and how can we do it?

**Comment by koenderks** [comment]
Hi @bekirburakcelik,

You can specify a custom theme using a named list (see https://github.com/koenderks/rcityviews#styling-the-map at the bottom). This way you can, for instance, not render the buildings. For example, this code renders just the streets because the buildings and contours have `NA` as a color here:

```
# For example: black, beige and white theme, streets only
myTheme <- list(
  colors = list(
    background = "#232323",
    water = NA,
    landuse = NA,
    contours = NA,
    streets = "#d7b174",
    rails = c("#d7b174", "#232323"),
    buildings = NA,
    text = "#ffffff",
    waterlines = NA
  ),
  font = list(
    family = "serif",
    face = "bold",
    scale = 1,
    append = "\u2014"
  ),
  size = list(
    borders = list(
      contours = 0.15,
      water = 0.4,
      canal = 0.5,
      river = 0.6
    ),
    streets = list(
      path = 0.2,
      residential = 0.3,
      structure = 0.35,
      tertiary = 0.4,
      secondary = 0.5,
      primary = 0.6,
      motorway = 0.8,
      rails = 0.65,
      runway = 3
    )
  )
)
cityview(name = "Rio de Janeiro", zoom = 0.5, theme = myTheme, border = "square", filename = "Rio.png")
```

Furthermore, you can delete the city name by calling `new_city()` and providing an empty name:

```
city <- new_city(name = "", country = "", lat = 37.10, long = -8.68)
cityview(name = city, filename = "Lagos.png")
```

Or you can delete all text (including coordinates) by setting the `text` entry in the theme list to `NA` or the background color.

**Comment by koenderks** [comment]
For future reference, another way to get the contents of the pre-specified themes is by running:

```
myTheme <- rcityviews:::.themeOptions("vintage")
```
