### ISSUE TITLE
git history is huge 

### ISSUE THREAD

**Issue by KlausVigo** [koenderks/rcityviews#8]
Hi @koenderks,  
first `rcityviews` is a really nice package. However when I want to create a project from a fork I realized this will several GB, as the picture png/daily.png is updated several times a day. Would it be possible to add this file in the `.gitignore` and maybe clean up the history? Unfortunately my knowledge about git is limited ([xkcd](https://xkcd.com/1597/)). 
Kind regards, 
Klaus

**Comment by koenderks** [comment]
Hi @KlausVigo,

First, thanks! This is a problem indeed. I've just cleared the commit history to make it feasible again to fork this project. However, I don't think I can add the daily png file to the `.gitignore` because a change has to be indicated in this repo in order for the twitter bot in another repo to post the image. I will look if I can amend the daily files into the previous commit, or if there is a better solution to keep the commit history clean.

Koen

**Comment by koenderks** [comment]
Ok I've made it so that every time a new image is made, it is merged into the previous commit. That way we should be able to keep the git commit history clean!

**Comment by KlausVigo** [comment]
Hi @koenderks, 
looks fine to me. I am not sure what the most elegant solution would be, but this seems to work. 
Thanks, 
Klaus
